name: mtf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - numpy
  - matplotlib
  - scipy
  - pip
  - qgis
  - jupyter
  - ipywidgets
  - pip:
    - loess==2.1.2
    - scikit-image